project:
  type: website
  output-dir: docs
  resources:
  - CNAME

website:
  title: "COVEREDINBEES / A hive of TLDR & villainy"
  site-url: https://coveredinbees.org
  description: "A hive of TLDR and villainy"
  margin-header: subscribe.html
  navbar:
    logo: images/cib_stripes.png
    right:
      - about.qmd
      - text: 'exobrain'
        href: https://exobrain.coveredinbees.org
      - icon: github
        href: https://github.com/DanOlner
      - icon: linkedin
        href: https://www.linkedin.com/in/danolner/
      - text: '{{< iconify simple-icons:bluesky title=bluesky >}}'
        href: https://bsky.app/profile/danolner.bsky.social
      - text: "{{< iconify simple-icons:wordpress title=wordpress_site >}}"
        href: https://www.danolner.net/
      - icon: rss
        href: index.xml
format:
  html:
    theme: darkly
    fontsize: 1.4em
    css: styles.css

#See here for using iconify in Quarto: https://github.com/quarto-dev/quarto-cli/discussions/5816#discussioncomment-6091449
#Install this (can use RStudio terminal): https://github.com/mcanouil/quarto-iconify
#Use this e.g. for Bluesky: https://icon-sets.iconify.design/simple-icons/bluesky/ 